# SPDX-License-Identifier: MIT
name: openEuler tests
on: [workflow_dispatch, push, pull_request]

jobs:
  openEuler:
    name: OpenEuler tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          - bm_empty
          - mysql/min_mysql_close_dup_0_0
          - mysql/min_mysql_getdents64_close_0_0
          - mysql/min_mysql_lseek_read_1_0
          - mysql/min_mysql_newfstatat_0_1
          - mysql/min_mysql_newfstatat_openat_0_1
          - mysql/min_mysql_openat_fsync_0_2
          - mysql/min_mysql_pread64_faccessat2_0_5
          - mysql/min_mysql_read_close_0_0
          - mysql/min_mysql_read_write_0_1

    env:
      TEST_TAG: ghcr.io/${{ github.repository }}/openeuler_for_csb:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Test ${{ matrix.test }}
        run: |
          mkdir /tmp/csb
          cp -ar . /tmp/csb

          docker run --rm --name csb \
            -v /tmp/csb:/home/csb \
            -v /boot:/boot \
            -v /lib/modules:/lib/modules \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /root/csb \
            --privileged \
            ${{ env.TEST_TAG }} \
            bash -c "cd /home/csb && git config --global --add safe.directory /home/csb && scripts/fg-diff/run-single.sh config/${{ matrix.test }}.json"

        # FIXME: ideally, we should be copying the already prepared /venv, but
        # the command line below didn't work:
        #            bash -c "cd /home/csb && cp -r /venv . && git config --global --add safe.directory /home/csb && scripts/fg-diff/run-single.sh config/${{ matrix.test }}.json"

      - name: Fix artifact permissions
        if: always()
        run: |
          sudo chmod -R a+r /tmp/csb/results/

      - name: Create unique name
        run: echo "ARTIFACT_NAME=$(echo '${{ matrix.test }}' | tr '/' '_')" >> $GITHUB_ENV

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: openeuler-results-${{ env.ARTIFACT_NAME }}
          path: /tmp/csb/results/
